### PR TITLE
Update httpAdapter.js

### PR DESCRIPTION
**Pull request by tiwariarvin**
Use encodeURI to process query strings with spaces and other such characters.
batchBody.push(request.method + ' ' + encodeURI(urlInfo.relativeUrl) + ' ' + constants.httpVersion);

### CODE REVIEW

**Comment by jonsamwell** [comment]
@tiwariarvin great spot and thanks for the PR.  Again could you add a simple test to prove functionality.

**Comment by jonsamwell** [comment]
I'll sort the test out so thanks for the PR!

**Comment by jonsamwell** [comment]
This fix is now in the new release (v1.11.3).
Here is the test I added for it
https://github.com/jonsamwell/angular-http-batcher/blob/master/tests/services/adapters/httpAdapter.spec.js#L123

**Comment by tiwariarvin** [comment]
Thanks Jonsamwell, 
Sorry that could not include test as was occupied with work for a product we are wrapping up.

Cheers
Arvin

**Pull request merged**
