### PR TITLE
Adding support for java servlet spec <= 3.1 and Spring MVC, to deal w…

### PR DESCRIPTION
**Pull request by jsnbuchanan**
Please feel free to accept or reject this pull request. If I have time later this week, I'll create a Spring Boot example of what the Server side parsing looks like. It's not nearly as simple as .NET, unfortunately.

Adding support for java servlet spec <= 3.1 and Spring MVC, to deal with the way multipart requests are parsed in Java Servlets. Hopefully this does not negatively impact .NET implementations, but I don't have the bandwidth to test this currently.

### CODE REVIEW

**Comment by jonsamwell** [comment]
Sorry for the delay!  Looking at this now!

**Comment by jonsamwell** [comment]
Hi @jsnbuchanan, I'm really sorry for the delay in doing this.  I sat down this morning and gone through the PR.  I feel that we shouldn't be introducing specific code fixes for platform directly into the library as it should remain as agnostic as possible.  After having a think I have added the ability to add additional headers to the batch request and it child parts so you can add this content-disposition header easily.  

https://github.com/jonsamwell/angular-http-batcher/blob/master/src/services/httpBatcher.js#L175
https://github.com/jonsamwell/angular-http-batcher/blob/master/src/services/httpBatcher.js#L187

Please see the readme for configuration to enable the java servlet headers https://github.com/jonsamwell/angular-http-batcher#configuring-for-java-servlet--31.  

Could you give it a try and see if it works.  If not come back to me and we'll look again.

Many thanks,

Jon

**Comment by jsnbuchanan** [comment]
Thank you Jon, I will give it a shot when time avails. :) I totally understand the being busy thing.

**Comment by LeeU1911** [comment]
Hi @jsnbuchanan, I'm looking for a configuration/implementation on the backend part in order to work with this angular-http-batcher library. Have you got a chance to post a Spring Boot example?

Thanks,

**Pull request closed without merging**
