### PR TITLE
Add unique request part names to Content-Disposition header

### PR DESCRIPTION
**Pull request by jeremymefford**
When you added the batchPartRequestHeader that made it nearly possible to use your library with java/tomcat, but I had to add one more piece.  This will append a unique name for each result to the content disposition header, which is apparently required for a tomcat servlet 3.1 application.

I also updated the processing of the Content-Type header to allow for other pieces of data to be sent after the boundary and still parse out the boundary correctly.

### CODE REVIEW

**Comment by jonsamwell** [comment]
Hi @jeremymefford! Thanks for this.  The PR looks good.  Could you just revert the changes to files in the dist folder, package and bower.json files as the build handles this.  Once that is done I'll accept the PR and do another release.

**Comment by jeremymefford** [comment]
@jonsamwell I have removed those changes, thanks for your quick response!

**Comment by jonsamwell** [comment]
I'll do a release of this tomorrow.  Sorry for the delay!

**Comment by jeremymefford** [comment]
No worries, thanks!

**Comment by jonsamwell** [comment]
Sorry for the delay this is now in the latest release v1.12.0

**Pull request merged**
