### PR TITLE
Support AngularJS's JSON Vulnerability Protection prefix

### PR DESCRIPTION
**Pull request by riaann**
Avoids an error on parsing responses that occurs when the AngularJS JSON
Vulnerability Protection prefix, ")]}'," is added to responses.  See
https://docs.angularjs.org/api/ng/service/$http#json-vulnerability-protection
for more details.

Includes a unit test to test for this scenario.

### CODE REVIEW

**Comment by jonsamwell** [comment]
Thanks for this!!!

I've just completely re-factored the library to work with the idea of adapters that are responsible for transforming multiple http requests into a single batch request and then parse the batch response back in multi responses (see the default adapter https://github.com/jonsamwell/angular-http-batcher/blob/master/src/services/adapters/httpAdapter.js).  The idea being the library can now support multiple different batching technologies i.e. http 1.1, node js implementations, Facebook etc.

So unfortunately your pull request will now have conflicts, but its a great addition and I really want it in!  I need to do up a bit of a util service to do things like url parsing etc where we could put this vulnerability protection function so all the adapters could use it.

I'll get the util in tomorrow if you want to update the pull request or I can put it in if you would rather?

Thanks again!!!

Jon

**Comment by jonsamwell** [comment]
I've added this here now and credited you in the change log.

https://github.com/jonsamwell/angular-http-batcher/blob/master/src/services/httpBatcher.js#L55
https://github.com/jonsamwell/angular-http-batcher/blob/master/dist/ChangeLog.txt#L3

Thanks very much for this!!!

**Comment by riaann** [comment]
Sorry for only seeing this now - am on leave, so wasn't keeping up with
email. Otherwise I would gladly have updated the pull request.

Thank you for giving me credit anyway! :)

**Comment by jonsamwell** [comment]
No thank you for submitting it!  I've given the library a really heavy refactor and it is much better because of it.  Anyway thanks again and really glad you are using the module.  Let me know if you have any other features ideas for the library and feel free to send other pull requests in!

**Pull request closed without merging**
